# Generated by Django 5.1 on 2024-08-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="ai_summary",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="cumulative_summary",
            field=models.TextField(default="abc"),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="summary",
            field=models.CharField(default="abc", max_length=200),
        ),
    ]
