# Generated by Django 5.1 on 2024-08-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_remove_journalentry_ai_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="embedding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
